import{a as S,S as v,i as a}from"./assets/vendor-73qhTu8_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&i(p)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const q="https://pixabay.com/api/",M="55691609-a8828a4d73b13042c91b577cc";async function y(s,e){const o={key:M,q:s,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0},i=await S.get(q,{params:o});return await new Promise(t=>setTimeout(t,1e3)),i.data}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new v(".gallery a",{captionsData:"alt",captionDelay:"250"});function g(s){const e=s.map(o=>`<li class='card'>
                <a class='gallery-link' href='${o.largeImageURL}'>
                    <img src=${o.webformatURL} alt=${o.tags} width='360' />
                </a>
                <div class='desc-wrapper'>
                    <p><span>Likes</span> ${o.likes}</p>
                    <p><span>Views</span> ${o.views}</p>
                    <p><span>Comments</span> ${o.comments}</p>
                    <p><span>Downloads</span> ${o.downloads}</p>
                </div>
            </li>`).join("");h.insertAdjacentHTML("beforeend",e),R.refresh()}function P(){const s=document.querySelector(".card").getBoundingClientRect();scrollBy({top:s.height*2,behavior:"smooth"})}function $(){h.innerHTML=""}function L(){f.style.display="block"}function d(){f.style.display="none"}function b(){m.style.display="block"}function l(){m.style.display="none"}const u=document.querySelector(".form"),B=document.querySelector(".load-more");let c="",n=1;const w=15;d();u.addEventListener("submit",s=>{s.preventDefault(),c=u.elements.search.value,n=1,u.reset(),$(),L(),l(),c.trim()&&y(c,n).then(e=>{e.hits.length>0?(n>=Math.ceil(e.totalHits/w)?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b(),g(e.hits)):a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(e=>{a.error({message:e.message,position:"topRight"})}).finally(d)});B.addEventListener("click",s=>{n+=1,L(),l(),y(c,n).then(e=>{e.hits.length>0?(n>=Math.ceil(e.totalHits/w)?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b(),g(e.hits),P()):a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(e=>{a.error({message:e.message,position:"topRight"})}).finally(d)});
//# sourceMappingURL=index.js.map
