import{a as S,S as v,i as a}from"./assets/vendor-73qhTu8_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const q="https://pixabay.com/api/",M="55691609-a8828a4d73b13042c91b577cc";async function y(s,e){const t={key:M,q:s,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await S.get(q,{params:t})).data}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),P=new v(".gallery a",{captionsData:"alt",captionDelay:"250"});function g(s){const e=s.map(t=>`<li class='card'>
                <a class='gallery-link' href='${t.largeImageURL}'>
                    <img src=${t.webformatURL} alt=${t.tags} width='360' />
                </a>
                <div class='desc-wrapper'>
                    <p><span>Likes</span> ${t.likes}</p>
                    <p><span>Views</span> ${t.views}</p>
                    <p><span>Comments</span> ${t.comments}</p>
                    <p><span>Downloads</span> ${t.downloads}</p>
                </div>
            </li>`).join("");h.insertAdjacentHTML("beforeend",e),P.refresh()}function R(){h.innerHTML=""}function L(){f.style.display="block"}function p(){f.style.display="none"}function b(){m.style.display="block"}function c(){m.style.display="none"}const d=document.querySelector(".form"),$=document.querySelector(".load-more");let i="",n=1;const w=15;p();d.addEventListener("submit",async s=>{if(s.preventDefault(),i=d.elements.search.value,n=1,d.reset(),R(),c(),!!i.trim())try{L();const e=await y(i,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits);const t=Math.ceil(e.totalHits/w);n>=t?(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(e){a.error({message:e.message,position:"topRight"})}finally{p()}});$.addEventListener("click",async s=>{n+=1,c();try{L();const e=await y(i,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),B();const t=Math.ceil(e.totalHits/w);n>=t?(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(e){a.error({message:e.message,position:"topRight"})}finally{p()}});function B(){const s=document.querySelector(".card").getBoundingClientRect();scrollBy({top:s.height*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
